title : Sakarin blogi
tagline: Blog Tagline
author :
  name : Sakari Cajanus
  email : blah@email.test
  github : sakkemo
  #twitter : username
  #feedburner : feedname

navigation :
  - archive.html
  - tags.html
  - categories.html
  - pages.html
  - about.md
  
